### ISSUE TITLE
Bot not receiving all channel messages as described in the document

### ISSUE THREAD

**Issue by Chloe959** [OfficeDev/Microsoft-Teams-Samples#452] opened 2022-08-26 08:15 UTC
I found that bot is not receiving all channel messages (unless it's explicity mentioned) despite having the ChannelMessage.Read.Group RSC permission.

Besides, according to the update of app studio, we can't have the same structure of "webApplicationInfo" in Manifest.json. The example in doc is that 
![image](https://user-images.githubusercontent.com/110153200/186855069-5096914b-7058-4024-8eeb-5a2b54faafc3.png)

but now, it should be like 
![image](https://user-images.githubusercontent.com/110153200/186855225-310201f8-718e-46e0-8e28-efa2daeb52b6.png)

The ""permissions": [ "identity", "messageTeamMembers" ],"  also posts an error when uploading the manifest.json.

Based on the document, with the ChannelMessage.Read.Group RSC permission, bot is expected to receive all messages even when not mentioned.

I turn my teams to Developer Preview but it still doesn't work.

Please help with this issue. Thanks!

**Comment by Nivedipa-MSFT** [comment] 2022-08-26 08:31
@Chloe959 - Closing this issue as a duplicate of #https://github.com/MicrosoftDocs/msteams-docs/issues/6771. Please feel free if reopen required.

**Closed by Nivedipa-MSFT** 2022-08-26 08:31 UTC
