### ISSUE TITLE
sample "Proactive message bots app" missing AAD environment variabes when provision into azure env

### ISSUE THREAD

**Issue by ayachensiyuan** [OfficeDev/Microsoft-Teams-Samples#1423] opened 2024-10-15 02:22 UTC
I use VSC teams toolkit to create sample "Proactive message bot" in sample gallery. 
Sample: [https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging-teamsfx](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging-teamsfx)
When I provision in to azure, I have following issue.
<img width="1648" alt="image" src="https://github.com/user-attachments/assets/847ba663-41b2-466c-a265-706eaf14e3e5">

**Comment by Nivedipa-MSFT** [comment] 2024-10-15 06:37
@ayachensiyuan - Thanks for reporting your issue. We will check and update you soon.

**Comment by ayachensiyuan** [comment] 2024-10-18 07:47
@Nivedipa-MSFT thank for your reply. I still face this issue, the version of TTK is the same. It works in local debug. but when I run provision in to AZURE, it failed with that error.

**Comment by Nivedipa-MSFT** [comment] 2024-10-18 09:49
@ayachensiyuan - Could you please verify that all necessary environment variables are correctly set in your Azure portal?
Verify that your Azure resources are properly configured and that you have the required permissions?

**Comment by ayachensiyuan** [comment] 2024-10-21 03:37
@Nivedipa-MSFT We have daily auto test for TTK, So this sample in TTK gallery failed since half month ago. Usually we test it according to readme file, It is certain that using the current version of TTK to create this sample and following the instructions in the readme to provision and deploy will encounter the problems mentioned above.  All of this was automatically deployed by TTK, and I did not have to manually operate on Azure. Here's the test: https://github.com/OfficeDev/teams-toolkit/actions/runs/11419663804/job/31778539159

**Comment by Nivedipa-MSFT** [comment] 2024-10-23 06:39
@ayachensiyuan - We have tested this on our end but were unable to reproduce the issue. Could you please clone the latest repository and test again?

**Comment by ayachensiyuan** [comment] 2024-10-24 06:59
Double confirm with you the repo steps: 
- clone the latest sample repository main branch
- switch the folder root to bot-proactive-messaging-teamsfx
<img width="472" alt="image" src="https://github.com/user-attachments/assets/48b1e7d0-4204-4f28-bcca-7327e5d4f356">
- open sidebar teams toolkit extension
- login azure and m365 account
- click provision button and fill in prompt information
<img width="478" alt="image" src="https://github.com/user-attachments/assets/c2305d77-14f8-40c2-8bf2-ea178c90beaf">
- wait for error log

**Comment by Nivedipa-MSFT** [comment] 2024-11-18 07:04
Closing this issue for now. Please free to reopen if required.

**Closed by Nivedipa-MSFT** 2024-11-18 07:04 UTC
Labels: sample-issue
