### ISSUE TITLE
Graph-RSC sample are not working as expected

### ISSUE THREAD

**Issue by diegoriera** [OfficeDev/Microsoft-Teams-Samples#1112] opened 2024-01-16 20:51 UTC
The sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc/csharp have two issues.

1 - When try to install the app as a tab, the Save button keep greyed out.
2 - The app show a message indicating that, the activity feed was sent successfully, however is not possible to see the activity feed on Teams client. 

The sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc/nodeJs also have issues.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/15849138/348144d8-ac6a-4b73-affb-f71fd3d07a25)

**Comment by Prasad-MSFT** [comment] 2024-01-17 05:40
@diegoriera - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment] 2024-01-17 14:07
@diegoriera - We tried to repro this issue and can confirm that the issue is happening at our end as well.

For this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc/csharp 
1 - When try to install the app as a tab, the Save button keep greyed out. - _We are checking this with concerned team and will update you accordingly once fix is done._
2 - The app show a message indicating that, the activity feed was sent successfully, however is not possible to see the activity feed on Teams client. - _There is an ICM raised for this and once we get any update from engineering team, we will inform you._


For this sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-rsc/nodeJs also _we are checking this with concerned team and will update you accordingly once fix is done._

**Comment by keeth** [comment] 2024-01-17 18:45
I am also looking at the `graph-rsc` demo (nodeJs version) and I can confirm that it has a number of serious issues, including undefined variables, misnamed variables, and improper use of async/await, which prevent it from running at all.  It's not ready for public consumption, as far as I can tell.

I have fixed all the bugs locally but it appears that the demo doesn't have enough permission to fetch the installed apps list.  

In the "sendNotification" server handler, it fails at this point:

```
GET https://graph.microsoft.com/v1.0/users/a4c851cd-7e9c-48af-bff0-de1931ee5019/teamwork/installedApps/?$expand=teamsAppDefinition

Missing role permissions on the request. API requires one of 'TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteAndConsentSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All, TeamsAppInstallation.ReadWriteAndConsentForUser.All, TeamsAppInstallation.ReadWriteForUser.Selected'. Roles on the request ''.
```

**Comment by keeth** [comment] 2024-01-17 20:12
I opened PR #1114 with all of my fixes to the nodeJs demo.  There were so many problems with this code :(

After approving the `TeamsAppInstallation.ReadForUser.All` in AAD, the demo worked and the notification was sent successfully.

**Comment by Prasad-MSFT** [comment] 2024-01-24 10:06
This [PR](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1120) has been raised and merged with 'Save button greyed out' fix.

**Comment by xzf0587** [comment] 2024-02-02 08:54
> I opened PR #1114 with all of my fixes to the nodeJs demo. There were so many problems with this code :(
> 
> After approving the `TeamsAppInstallation.ReadForUser.All` in AAD, the demo worked and the notification was sent successfully.

Yes. I tried the node.js version and it does not work. My fix is similar to yours

**Comment by Prasad-MSFT** [comment] 2024-02-26 05:26
The PR has been merged. Please do verify the fix.

**Closed** 2024-03-03 12:45 UTC
Labels: status-no-recent-activity, needs-author-feedback, sample-issue
