### ISSUE TITLE
On Microsoft teams when I click allow permission to download file. I got something went wrong message

### ISSUE THREAD

**Issue by ChernHwee** [OfficeDev/Microsoft-Teams-Samples#632] opened 2022-12-16 01:41 UTC
## Describe the bug
On Microsoft teams application. After I followed and ran [56.teams-file-upload](https://github.com/microsoft/BotBuilder-Samples/tree/22fcff680a3e11006eb09b81ac5ed4de345933e2/archive/samples/python/56.teams-file-upload), I have click allowed  and it shows the something went wrong message

## To Reproduce
1. Execute 56.teams-file-upload example
2. type something on the bot
3. Press allow in the upload permission

## Expected behavior
Upon clicking it, it should not show the something went wrong

## Screenshots
![image](https://user-images.githubusercontent.com/72246152/207523122-9fe831c0-8b00-4e81-be67-9a08d6cd4aaa.png)

**Comment by ChernHwee** [comment] 2022-12-16 01:41
Hi, this ticket is a duplication of https://github.com/microsoft/botframework-sdk/issues/6559
I was told to raised it here.

**Comment by Meghana-MSFT** [comment] 2022-12-16 06:47
@ChernHwee - Thank you for reporting this issue, we are also able to reproduce this issue with Python sample. We are checking this internally. Please be assured that we will get back to you with further update within 48 hours.

**Comment by ChernHwee** [comment] 2022-12-20 05:30
@Madhuri-MSFT , any updates about this issue?

**Comment by Meghana-MSFT** [comment] 2022-12-20 16:45
@ChernHwee - We are checking the different scenarios on what could be causing this issue. We will give you an update soon. Thanks.

**Comment by Meghana-MSFT** [comment] 2022-12-26 05:17
@ChernHwee - We have raised a bug for this issue, we will keep you posted if there are any updates on the bug. Thanks.

**Comment by singhk97** [comment] 2023-03-03 04:43
I have opened a PR that should fix the `Something went wrong. Please try again` message when it shouldn't happen. Now if it is happening because the server is taking long to response, that is expected behavior.

**Comment by ChetanSharma-msft** [comment] 2023-12-18 06:01
Hello @singhk97 - Could you please raise the PR against this repo and project?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload/python

**Comment by ChetanSharma-msft** [comment] 2024-02-26 06:32
Sample is fixed and PR is merged.

We are closing this issue, please feel free to reopen it if required.

**Closed** 2024-02-26 06:32 UTC
Labels: bug, pr-raised, sample-issue
