### ISSUE TITLE
[bot-type-ahead-search-adaptive-cards][csharp] selecting item from dynamic choice set shows error

### ISSUE THREAD

**Issue by kuojianlu** [OfficeDev/Microsoft-Teams-Samples#868] opened 2023-07-20 07:42 UTC
Bug description:
For sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp.
After selecting an item from the dynamic choice set, Adaptive Card shows below error, and the "Submit" button does not work.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/37978464/f5419f86-c072-4230-96d3-7c87315ad38a)

Reproducing steps:
1. Send "dynamicsearch" command to bot.
2. Search a query like "Microsoft" in the Adaptive Card input box.
3. Select an item from the search result list.
4. Click "Submit" button. There is no response for the clicking operation.
5. If adding "errorMessage" setting to `DynamicSearchCard.json` like below, then after selecting an item, the error message will show in the Adaptive Card.
```json
          "items": [
            {
              "choices": [
                {
                  "title": "Static Option 1",
                  "value": "static_option_1"
                },
                {
                  "title": "Static Option 2",
                  "value": "static_option_2"
                },
                {
                  "title": "Static Option 3",
                  "value": "static_option_3"
                }
              ],
              "isMultiSelect": false,
              "style": "filtered",
              "choices.data": {
                "type": "Data.Query",
                "dataset": "npmpackages"
              },
              "id": "choiceSelect",
              "type": "Input.ChoiceSet",
              "errorMessage": "There was an error", // ADD THIS SETTING
            }
          ],
```

**Comment by Meghana-MSFT** [comment] 2023-07-20 10:12
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment] 2023-07-20 14:22
@kuojianlu - We ran the https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp sample and it is working fine at our end. 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/0b07d40f-d4f2-47a4-b48d-244b0d2ddcbc)

We checked in Teams web app in Windows. Could you please let us know the OS or app version details which could help us in having a repro.

**Comment by kuojianlu** [comment] 2023-07-24 10:11
@Meghana-MSFT Thank you for replying. I also use Teams web app in Windows.

OS: Windows_NT x64 10.0.23486
Teams version: Developer preview

I just tried the demo-manifest (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp/demo-manifest) as well, it also did not work on my side. The "Submit" button did not work.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/37978464/b1bac4dc-2e7b-449e-9f26-066709f592c7)

**Comment by Meghana-MSFT** [comment] 2023-07-25 13:43
Could you please share test account credentials where this issue is reproducible? Please share the credentials at microsoftteamsdev@microsoft.com.

**Comment by Meghana-MSFT** [comment] 2023-08-02 12:50
@kuojianlu - We raised bug for this issue, we will keep you posted on the updates.

**Comment by CodeABao** [comment] 2023-08-15 06:46
any updates?

**Comment by AleVitali** [comment] 2023-08-24 16:35
Maybe this can help to find the issue: if I insert into the `choice` field an array with the possible values with an explicit `"type": "Insert.Choice"` works.

I tried to return that field from my backend, but it's filtered.

**Comment by Meghana-MSFT** [comment] 2023-08-28 06:43
Unfortunately, we do not have an ETA to share. Team is working on the bug; we will keep you posted on the updates. Thank you.

**Comment by ChetanSharma-msft** [comment] 2023-12-27 08:56
Hello Everyone,
This issue is fixed now. 
Could you please verify once and let us know the updates?

**Closed** 2024-01-05 05:19 UTC
Labels: bug, status-no-recent-activity, needs-author-feedback

**Comment by dylanw-oss** [comment] 2024-03-10 05:28
I can still repo the issue

**Comment by dylanw-oss** [comment] 2024-03-10 05:36
> Hello Everyone, This issue is fixed now. Could you please verify once and let us know the updates?

The fix does not work, I can still repo the issue in JS sample, using Teams web.

**Comment by AleVitali** [comment] 2024-03-11 09:44
We had to drop the feature as, when we tried to select an option, the validation failed complaining about a missing value

**Comment by SandeepGamot** [comment] 2024-03-20 09:17
This is still a problem in Teams web.

**Comment by Meghana-MSFT** [comment] 2024-03-26 12:28
Since another issue has been raised for this, we will track the issue in above mentioned thread. #https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1213
