### ISSUE TITLE
Real time meeting events not firing up

### ISSUE THREAD

**Issue by juanmanuelpuhl** [OfficeDev/Microsoft-Teams-Samples#193] opened 2021-11-11 17:46 UTC
I've been following the sample for real time meeting events ([here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-events/nodejs)) in nodejs. I created a new bot just for this, set up ngrok and ran the server. Modified the manifest with my bot id and then created the package to sideload.
Then I created a meeting, added the app and then started it, but I didn't get the notification for meeting start. I can get the other events, like message, memberAdded and memberRemoved. Manifest is in version 1.10, and I tried with and without public dev preview enabled.

I tried several times and checked I have the right permission `OnlineMeeting.Readbasic.Chat` and I do. 

It isn't something about the node code, the thing is that I'm not receiving the POST request on my ngrok server just for those two events (meeting start and meeting end), so I can't really process it.

Can you guys investigate this and see if these notifications are working?

**Comment by Prasad-MSFT** [comment] 2021-11-12 14:20
@juanmanuelpuhl , We are also able to repro this issue at our end. We are checking this internally and will get back to you once we get any update.

**Comment by Prasad-MSFT** [comment] 2021-11-17 15:26
@juanmanuelpuhl , We have a bug raised for this issue and concerned team is looking into it. We will inform you once we get any update.
Thanks!

**Comment by Prasad-MSFT** [comment] 2021-12-08 05:21
@juanmanuelpuhl - We got confirmation from engineering team that the issue is fixed now. Please upgrade your MS Teams client and check.
Closing the issue for now. Please feel free to re-open if required.

**Closed by Prasad-MSFT** 2021-12-08 05:21 UTC
