### ISSUE TITLE
Anonymous user can't view the stage for app-anonymous-users sample

### ISSUE THREAD

**Issue by tinsheep** [OfficeDev/Microsoft-Teams-Samples#736] opened 2023-03-08 00:44 UTC
When i share the stage it is not visible for the anonymous user. I get the "App sharing in progress - Someone is sharing an app to this meeting (see attached) . This experience isn't supported in the Teams web app" I used the supplied manifest including the supportsAnonymousGuestUsers = true, followed instructions for anonymous users being able to interact with apps in meetings, etc.  Any idea what else i could be missing?

Thanks,
mp
[Microsoft-Teams-Samplessamplesapp-anonymous-userscsharp at main · OfficeDevMicrosoft-Teams-Samples · GitHub.pdf](https://github.com/OfficeDev/Microsoft-Teams-Samples/files/10915294/Microsoft-Teams-Samplessamplesapp-anonymous-userscsharp.at.main.OfficeDevMicrosoft-Teams-Samples.GitHub.pdf)

**Comment by sayali-MSFT** [comment] 2023-03-08 11:17
@tinsheep - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by Githamza** [comment] 2023-03-09 13:43
I have the same issue, I get the same message

**Comment by Githamza** [comment] 2023-03-13 09:29
@tinsheep  can you test today and tell me if it's working ?

**Comment by tinsheep** [comment] 2023-03-15 03:30
@Githamza I grabbed the latest from the samples and tried again today and its the same thing but i wouldn't have expected anything as the code hasn't been updated, at least on the C# side. I did see that it does work in the mobile client as anonymous but I think that has been working for some time. I need it to work on the web like the sample illustrates. 

@sayali-MSFT are there any updates please? Thanks.

**Comment by sayali-MSFT** [comment] 2023-03-15 05:53
@tinsheep -We are checking with the latest update and let you know.

**Comment by Githamza** [comment] 2023-03-15 11:14
Is the anonymous feature works only on desktop app ?

**Comment by sayali-MSFT** [comment] 2023-03-15 11:25
@Githamza -It is working on Web as well.

https://user-images.githubusercontent.com/93527375/225295118-00b081ca-634e-4fd8-9e73-9e0081b2aa5b.mp4

**Comment by tinsheep** [comment] 2023-03-15 23:17
@sayali-MSFT Thank you very much for the repro. This is encouraging. You dont suppose my problem is that i initiated the meeting *from* the browser and not the Teams client, do you? One thing i noticed is that i did not have to consent to the RSC permission and don't see it granted for that chat in postman - see video at the end. Thanks again.

https://user-images.githubusercontent.com/8007578/225464724-04745a73-2a41-4fce-8dac-eb79b9c22fa9.mp4

**Comment by sayali-MSFT** [comment] 2023-03-16 05:02
@tinsheep - We are checking it internally and get back to you once we get any update.

**Comment by tinsheep** [comment] 2023-03-17 16:34
Something is weird @sayali-MSFT  - I tried the same app/build in a new tenant just to see and I saw it work just one time in the exact browser to browser scenario above. I tried again to record this time and I get the message above again. So it seems to be intermittent for me. Thanks again for staying on this. I'll keep trying.

**Comment by tinsheep** [comment] 2023-03-20 22:07
I got this working today - not sure if you want to keep it open or if you still want to try and resolve the web to web issue you were able to repro. Your call - i still think something might not be right but I can't nail it down. Thanks again.

https://user-images.githubusercontent.com/8007578/226476187-b9efe7ee-55ee-432a-ba92-b8033b1c442a.mp4

**Comment by Githamza** [comment] 2023-03-20 22:11
I'm going to test it also tomorrow. can you keep the issue open plz ? are you using nodejs or cshap in your app ?

**Comment by tinsheep** [comment] 2023-03-20 22:13
C#

**Comment by Githamza** [comment] 2023-03-27 00:23
I have tried today with manifest 1.16 and supportsAnonymousGuestUsers parameter , I'm getting the same error 

https://user-images.githubusercontent.com/11578288/227814337-344b1e43-0bfb-4e72-ad34-c232f900aa8b.mov

**Comment by sayali-MSFT** [comment] 2023-03-27 04:06
@Githamza -We have already raised bug for the same, We will inform you once we get any update.

**Comment by ChetanSharma-msft** [comment] 2023-05-15 06:26
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by Githamza** [comment] 2023-06-06 10:47
any news ?

**Comment by sayali-MSFT** [comment] 2023-12-08 12:47
@tinsheep -We got the reply from engineering team that, This is by design. The Teams web accessed by anon user is in Angular Teams. We do not support apps for anon users in angular Teams.

**Comment by sayali-MSFT** [comment] 2023-12-11 04:46
@Githamza -We will confirm with the engineering team and let you know the update.

**Comment by ChetanSharma-msft** [comment] 2023-12-28 09:09
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-12-28 09:09 UTC
Labels: bug, needs-author-feedback, by-design

**Comment by theogumilang** [comment] 2024-01-05 09:28
Hi can you reopen this issue, I have a problem when using anonymous users, it says can't show this content it says something went wrong.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/9142a025-36bc-4e59-a4bf-8c16ae8b2a6a)

**Comment by Githamza** [comment] 2024-01-05 12:53
Are you using the new or old teams ?
