### ISSUE TITLE
Error: botAadApp/create failed due to service management reference

### ISSUE THREAD

**Issue by yuting1008** [OfficeDev/Microsoft-Teams-Samples#1441] opened 2024-11-06 06:12 UTC
I am reproducing https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-expert-finder-js.
When setting up resources, I fail to run the app in a Teams web client.

>   (×) Error: botAadApp/create failed.
    (×) Error: Service management reference is required when creating Microsoft Entra app in Microsoft tenant. Please refer to the help link to provide a valid service management reference.
  (!) Warning: botFramework/create was not executed.
  (!) Warning: teamsApp/validateManifest was not executed.
  (!) Warning: teamsApp/zipAppPackage was not executed.
  (!) Warning: teamsApp/validateAppPackage was not executed.
  (!) Warning: teamsApp/update was not executed.
  (!) Warning: teamsApp/extendToM365 was not executed.

Below is the botAadApp/create.

```
  # Create or reuse an existing Azure Active Directory application for bot.
  - uses: botAadApp/create
    with:
      # The Azure Active Directory application's display name
      name: expert-finder-${{TEAMSFX_ENV}}
    writeToEnvironmentFile:
      # The Azure Active Directory application's client id created for bot.
      botId: BOT_ID
      # The Azure Active Directory application's client secret created for bot.
      botPassword: SECRET_BOT_PASSWORD
```

How to fix this issue? Thank you!

**Comment by sayali-MSFT** [comment] 2024-11-06 07:07
@yuting1008 - Thank you for your inquiry about your Teams app development issue! 
We will check this at our end and will get back to you.

**Comment by yuting1008** [comment] 2024-11-06 07:17
I try to follow **Case 2** solultion in the [help link](https://aka.ms/teamsfx/missing-service-management-reference-help) that the error message provides.

![image](https://github.com/user-attachments/assets/c723be62-1aaa-4a09-b420-57f8c85b31d4)

This is waht I have done:
1. Update teamsapp.yml and teamsapp.local.yml files to use aadApp/create action
2. Add BOT_OBJECT_ID to env/.env.{name} after updated the yaml file
3. (I am not sure waht "**provide service tree ID**" means in the instruction.)

But it doesn't work. The error message is as below. 
>   (×) Error: aadApp/create failed.
>     (×) Error: Service management reference is required when creating Microsoft Entra app in Microsoft tenant. Please refer to the help link to provide a valid service management reference.

**Comment by yuting1008** [comment] 2024-11-07 13:17
@sayali-MSFT I try the manifest you provide but it still doesn't work.

May I know what **"run the app in Team web client"** exactly is?
![螢幕擷取畫面 2024-11-07 210408](https://github.com/user-attachments/assets/71354ee9-ae4f-4f9c-b3b1-d977c69c5cda)

Which options should I use in **Start debugging**?
I have tried all of them but the app registration isn't created by the toolkit.
![image](https://github.com/user-attachments/assets/1408f0f7-bb73-4c6e-b151-0bdb55cbce42)
Thank you!

**Comment by yuting1008** [comment] 2024-11-07 13:28
@sayali-MSFT I tried the manifest you provided but it still doesn't work. Below is the complete error message when I run the app in Teams web client.

![image](https://github.com/user-attachments/assets/8cb31b14-c1fe-44a4-bd10-edc356a29aff)

**Comment by yuting1008** [comment] 2024-11-11 16:18
I kinda of solve the botAadApp/create problem by creating App Registration first and providing **BOT_ID** and **SECRET_BOT_PASSWORD**.

What I have done:
1. Create App Registration and generate a secrer
  ![螢幕擷取畫面 2024-11-11 232155](https://github.com/user-attachments/assets/38b9d2a3-7b55-4091-bf5a-28c5d212cf34)

2. Add **BOT_ID** to **env.local**
  <img width="740" alt="螢幕擷取畫面 2024-11-11 232325" src="https://github.com/user-attachments/assets/be0cf8a6-0bd2-487d-847a-72f0a5f3d9d6">

3. Add **SECRET_BOT_PASSWORD** to **env.local.user**

![螢幕擷取畫面 2024-11-11 232512](https://github.com/user-attachments/assets/e51fd401-8068-479c-b2f7-ca73978cbc38)

However, I am now facing other issue. According to the README, Azure bot will be created automatically in the selected subscription and resource group while running the sample using Toolkit.

![image](https://github.com/user-attachments/assets/97970fe5-8219-47c0-aeb3-2066dd087efe)

But The Azure Bot Service wasn't create automatically in my resource group. The Bot was created in **dev.framework.com** instead.

![螢幕擷取畫面 2024-11-11 233643](https://github.com/user-attachments/assets/6c13c58e-bfd3-44f9-8d4b-5d67f005144e)

And the APP was still unable to connect.

![image](https://github.com/user-attachments/assets/9cd2eba8-03fc-4f44-ac61-b85b1d008a66)

**Comment by sayali-MSFT** [comment] 2024-11-13 07:48
Hello @yuting1008,
Thank you for your report! We are currently unable to reproduce the issue you’re experiencing. Could you please provide the following information to help us better assist you? 

If available, please share any relevant error logs that you’ve received. 

This information will be invaluable in helping us understand the problem and find a solution.

**Closed** 2024-11-18 08:33 UTC
Labels: status-no-recent-activity, needs-author-feedback
