### ISSUE TITLE
Adaptive card Replacement issue in new pva preview  version

### ISSUE THREAD

**Issue by GouthamGoud03** [OfficeDev/Microsoft-Teams-Samples#816] opened 2023-05-29 09:36 UTC
Hi, 
In new pva preview version  I have created a flow with adaptive card . this card should be replace when I do submit  or cancel with in the adaptive card 
In new pva preview version i have found one option **Conversation update activity** 
find screenshot below
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81476480/d573b6de-3143-44b9-a49c-f382fb79c4ce)
this option is not working for conversation update.
so could you please provide details of this, how we can handle

thank you 
Goutham Pamula

**Comment by Prasad-MSFT** [comment] 2023-05-31 10:50
@GouthamGoud03 - Please refer [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/814) thread for further updates.

**Comment by ChetanSharma-msft** [comment] 2023-06-05 06:25
Closing as a duplicate of: https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/814

**Closed** 2023-06-05 06:25 UTC
