### ISSUE TITLE
Accessing microphone in the desktop client from a tab application.

### ISSUE THREAD

**Issue by dermatologist** [OfficeDev/Microsoft-Teams-Samples#919] opened 2023-08-17 15:31 UTC
Do you happen to have a documented pattern for a Javascript (React) "tab" application that can have access to the microphone for speech-to-text? Currently, we are able to access the microphone on the MS Teams web client, but not on the desktop client.

**Comment by ChetanSharma-msft** [comment] 2023-08-18 04:51
Hello @dermatologist - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Sujanaalahari** [comment] 2023-08-31 16:46
Hi 

Following up on the above ask - Did we make any progress. 
Regards
Sujana (Same team as dermatologist)

**Comment by Prasad-MSFT** [comment] 2023-09-01 05:12
Hi @Sujanaalahari - At the moment, we have not received any updates from the engineering team. However, we are actively communicating with them to stay updated on the progress.  As soon as we receive any updates from them, we will notify you in this thread. Thank you!

**Comment by Prasad-MSFT** [comment] 2023-09-12 14:04
Hi @Sujanaalahari - We got update from engineering team that, "This behaviour is currently by design. The Teams Web/Desktop Client only supports the `selectMedia` API when it's called with `MediaType.Image`. The other types are not supported."

**Comment by dermatologist** [comment] 2023-09-12 14:11
@Prasad-MSFT : So, is it impossible to enable the microphone in a Tab application, or is there any other pattern we can follow? The use case is to have speech -> text in a tab.

**Comment by ChetanSharma-msft** [comment] 2023-09-15 16:51
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by ChetanSharma-msft** 2023-09-15 16:51 UTC
Labels: bug
