### ISSUE TITLE
bot : Conversation reference is undefined

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/Microsoft-Teams-Samples#155] opened 2021-09-22 20:02 UTC
I'm running the in meeting app sample.

I have configured the app 
1. Created a meeting.
2. Added a member.
3. Added the custom app.
4. Started the meeting

![image](https://user-images.githubusercontent.com/11578288/134409248-dfcac2c2-2e6c-48e7-99bd-48fd293d498b.png)

When I try to click on "show in meeting dialog "  ,in the bot server I get this error ( botFrameworkAdapter.js ) when calling `/getParticipantInfos` endpoint

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'serviceUrl' of undefined
    at BotFrameworkAdapter.<anonymous> (/Users/hamzahaddad/Projects/teamsApp/in-meeting-app/bot/node_modules/botbuilder/lib/botFrameworkAdapter.js:193:82)
```

```
app.get("/getParticipantInfo", async (req, res) => {
  let participantId = jwt_decode(req.query.ssoToken)["oid"]; // Get the participant ID from the decoded token
  let tenantId = jwt_decode(req.query.ssoToken)["tid"]; // Get the tenant ID from the decoded token
  let meetingId = req.query.meetingId;
  let conversationReference = meetingInfoRepository.getConversationReference(
    req.query.conversationId
  ); // Look up the conversation reference object by conversation Id
  adapter.continueConversation(conversationReference, async (context) => {
    /**
     * Retrieve info using BF SDK
     * Learn more: https://docs.microsoft.com/en-us/javascript/api/botbuilder/teamsinfo?view=botbuilder-ts-latest#getMeetingParticipant_TurnContext__string__string__string_
     */
    let participantInfo = await TeamsInfo.getMeetingParticipant(
      context,
      meetingId,
      participantId,
      tenantId
    );
    console.log("Got role info: ", participantInfo);
    res.send(participantInfo);
  });
});
```
I see that `meetingInfoRepository` is undefined
I don't know how to set `conversationReference` value.

As I see the only place where `meetingInfoRepository` is set is in  `onTeamsMembersAddedEvent`

```
    this.onTeamsMembersAddedEvent(
      async (membersAdded, teamInfo, context, next) => {
        meetingInfoRepository.setMeetingContext(
          context.activity.conversation.id,
          context
        );
        await next();
      }
    );
```
What are the step to be able to set this value and trigger `show bot dialog` button.

**Comment by v-chetsh** [comment] 2021-10-01 18:43
@Githamza - Could you please share the Sample code URL,  so we will check & let you know.

**Comment by Meghana-MSFT** [comment] 2021-10-05 12:39
@Githamza - Please share the Sample code URL if you are still facing the issue.

**Comment by Githamza** [comment] 2021-10-05 15:27
Hi , I have resolved  my bug , It was because of app secret I was copying the secretID instead. I find this UI section is very misleading.

**Comment by Meghana-MSFT** [comment] 2021-10-05 17:44
Closing this as the issue is resolved.

**Closed by Meghana-MSFT** 2021-10-05 17:44 UTC
